# 服务器端口
server:
  port: 9091

# 服务名称
spring:
  application:
    name: minio-service

# 图片服务器 minio配置
minio:
  url: http://39.97.231.147:9001
  # minio登录账号密码
  accessKey: minio
  secretKey: minio123

  ## 桶名（文件夹）命名规则要符合 亚马逊S3标准 详情可看http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
  bucketName:
    ## 照片文件夹
    facility: file-root
  thumbor:
    #缩略图宽度
    width: 50

swagger:
  basePackage: com.itcast.minio.controller
  contactEmail: 2215751025@qq.com
  contactName: zheng.zhang
  contactUrl: https://github.com/EternityBQQ/CaEducation.git
  desc: Minio服务测试
  groupName: baseModule
  license: 涨涨开发
  licenseUrl: javascript:void(0)
  termsOfServiceUrl: javascript:void(0)
  title: 文件服务测试Swagger APIs
  version: 0.0.1.SNAPSHOT
